spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/employeeDB
    driver-class-name: org.postgresql.Driver
  config:
    import: "optional:configserver:"
  jpa:
    hibernate:
      ddl-auto: update


    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  zipkin:
    base-url: http://localhost:9411


logging:
  level:
    org.springframework: ERROR
    com.vkiprono: DEBUG
server:
  port: 9002
