spring:
  application:
    name: USER-SERVICE
  config:
    import: "optional:configserver:"
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/employeeDB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      uri: http://localhost:9193
      enabled: true
  zipkin:
    base-url: http://localhost:9411


server:
  port: 9003

logging:
  level:
    org.springframework: ERROR
    com.vkiprono: DEBUG


